version: '3.8'

services:
  mysql:
    container_name: community_feed_database
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: on-failure
    volumes:
      - ./data/mysql:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul
#      MYSQL_DATABASE: database`

